from pydantic import BaseSettings


class Settings(BaseSettings):
    project_name: str = 'Some project name'
    redis_host: str = ...
    redis_port: int = ...
    elastic_host: str = ...
    elastic_port: int = ...

    db_name: str = ...
    db_user: str = ...
    db_password: str = ...
    db_host: str = ...
    db_port: str = ...

    def pg_url(self):
        return f'postgresql+asyncpg://{self.db_user}:{self.db_password}@{self.db_host}:{self.db_port}/{self.db_name}'



settings = Settings()