repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/seed-isort-config
    rev: 'v2.2.0'
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
      - id: isort
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
        entry: black --skip-string-normalization
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        exclude: ^(tests/|alembic/)
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        require_serial: true
        exclude: ^(tests/|alembic/)
        args:
          - "--disable=R0903"
          - "--disable=C0114"
          - "--disable=C0115"
          - "--disable=C0116"
          - "--disable=E0401"
