"""user_role_permission_relations

Revision ID: 838c3d2e1c61
Revises: fbdc4be7f02a
Create Date: 2023-09-21 14:05:53.399705

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '838c3d2e1c61'
down_revision: Union[str, None] = 'fbdc4be7f02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolepermission',
    sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('permission_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_unique_constraint('uq_permission_name', 'permission', ['name'])
    op.create_unique_constraint('uq_role_name', 'role', ['name'])
    op.add_column('userroles', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('userroles', sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_index('ix_userroles_id', table_name='userroles')
    op.create_foreign_key('fk_userroles_role', 'userroles', 'role', ['role_id'], ['id'])
    op.create_foreign_key('fk_userroles_user', 'userroles', 'user', ['user_id'], ['id'])
    op.drop_column('userroles', 'id')
    op.drop_column('userroles', 'user_login')
    op.drop_column('userroles', 'user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userroles', sa.Column('user_role', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('userroles', sa.Column('user_login', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('userroles', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_userroles_role', 'userroles', type_='foreignkey')
    op.drop_constraint('fk_userroles_user', 'userroles', type_='foreignkey')
    op.create_index('ix_userroles_id', 'userroles', ['id'], unique=False)
    op.drop_column('userroles', 'role_id')
    op.drop_column('userroles', 'user_id')
    op.drop_constraint('uq_role_name', 'role', type_='unique')
    op.drop_constraint('uq_permission_name', 'permission', type_='unique')
    op.drop_table('rolepermission')
    # ### end Alembic commands ###
