"""Add refresh_token roles tables

Revision ID: e649c0842ea8
Revises: 39cdd7b3d498
Create Date: 2023-09-07 00:44:49.613179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e649c0842ea8'
down_revision: Union[str, None] = '39cdd7b3d498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('user_login', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
                    sa.Column('user_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_refreshtoken_id'), 'refreshtoken', ['id'], unique=True)
    op.create_table('role',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_refreshtoken_id'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
